[workspace]
members = ["crates/core", "apps/desktop/src-tauri"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
weave_core = { path = "crates/core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
dirs = "5.0"
