packages:
  - apps/*
  - packages/*
catalog:
  vue: ^3.5
  lexical: latest
  "@lexical/utils": latest
  "@lexical/text": latest
  "@lexical/clipboard": latest
  "@lexical/html": latest
  "@lexical/history": latest
  "@lexical/devtools-core": latest
  "@vanilla-extract/css": ^1.17
  "@vanilla-extract/recipes": ^0.5.5
  "@vanilla-extract/dynamic": ^2.1
