name: Deploy

on:
  push:
    branches:
      - main

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      playground: ${{ steps.filter.outputs.playground }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            playground:
              - 'packages/playground/**'
              - 'packages/editor/**'
              - 'packages/ui/**'
              - 'vite.config.*'

  build:
    needs: changes
    if: ${{ needs.changes.outputs.playground == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build Playground
        run: pnpm build:playground
      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/playground/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
